deploy_local:
  stage: deploy
  tags:
    - server
    - democoll
  only:
    - main
  variables:
    GIT_STRATEGY: none
  script:
    - echo "Deploy langsung di server (tanpa SSH).s.."
    - cd /var/www/democoll84/scoring_ci4_v1/
    - git fetch --all
    - git reset --hard origin/main
